begin;
do $test$
declare admin_actor uuid; resident_actor uuid; resident_record uuid; other_actor uuid:=gen_random_uuid(); a jsonb; b jsonb; result jsonb; quote numeric; request_id uuid; key uuid:=gen_random_uuid(); booking_date date:=((now() at time zone 'Asia/Manila')::date+90); stored_fee numeric; n integer;
begin
 select user_id into strict admin_actor from public.admin_profiles where is_active limit 1;
 select id,user_id into strict resident_record,resident_actor from public.residents where not exists(select 1 from public.admin_profiles p where p.user_id=residents.user_id and p.is_active) limit 1;
 insert into auth.users(id,email) values(other_actor,other_actor::text||'@test.invalid');
 perform set_config('request.jwt.claim.sub',admin_actor::text,true);execute 'set local role authenticated';
 a:=public.admin_system_analytics(null,null,'all');b:=public.admin_system_analytics('3000-01-01','3000-02-01','all');
 if jsonb_array_length(a->'charts')<>36 then raise exception 'FAIL: expected 36 analytics charts'; end if;
 if a->'residentTotal' is distinct from b->'residentTotal' or a->'addressGroups' is distinct from b->'addressGroups' then raise exception 'FAIL: activity date range changes current totals';end if;
 if exists(select 1 from jsonb_array_elements(b->'charts') c,jsonb_array_elements(c->'rows') r where (c->>'period')::boolean and (r->>'count')::integer>0) then raise exception 'FAIL: future activity range is not empty';end if;
 if a::text ~ 'first_name|last_name|contact_number|email_address|front_image_url|captured_face_url|residential_address' then raise exception 'FAIL: personal information in aggregate payload';end if;
 begin perform public.admin_system_analytics('2026-10-10','2026-10-01','all');raise exception 'FAIL: invalid date range';exception when invalid_parameter_value then null;end;
 if jsonb_array_length(public.get_service_catalog())<>2 then raise exception 'FAIL: approved catalog missing';end if;
 perform set_config('request.jwt.claim.sub',resident_actor::text,true);
 begin perform public.admin_system_analytics();raise exception 'FAIL: resident accessed admin analytics';exception when insufficient_privilege then null;end;
 if exists(select 1 from public.appointments where user_id<>resident_actor) then raise exception 'FAIL: resident reads other appointments';end if;
 begin update public.service_catalog set base_fee=999;raise exception 'FAIL: resident can change fee rules';exception when insufficient_privilege then null;end;
 while extract(isodow from booking_date)>5 loop booking_date:=booking_date+1;end loop;
 quote:=public.preview_appointment_fee(resident_record,'barangay_clearance',null);
 result:=public.book_resident_appointment(resident_record,'barangay_clearance',null,booking_date,'10:00','Enhancement regression fixture',quote+999,key);
 if coalesce((result->>'booked')::boolean,false) or not coalesce((result->>'fee_changed')::boolean,false) then raise exception 'FAIL: invalid expected fee accepted';end if;
 result:=public.book_resident_appointment(resident_record,'barangay_clearance',null,booking_date,'10:00','Enhancement regression fixture',quote,key);
 if not coalesce((result->>'booked')::boolean,false) then raise exception 'FAIL: valid booking not saved: %',result;end if;
 select id,fee into strict request_id,stored_fee from public.appointments where request_key=key;
 result:=public.book_resident_appointment(resident_record,'barangay_clearance',null,booking_date,'10:00','Enhancement regression fixture',quote,key);
 select count(*) into n from public.appointments where request_key=key;if n<>1 then raise exception 'FAIL: duplicate idempotent booking';end if;
 perform set_config('request.jwt.claim.sub',other_actor::text,true);
 if exists(select 1 from public.appointments where id=request_id) then raise exception 'FAIL: another resident reads request';end if;
 perform set_config('request.jwt.claim.sub',admin_actor::text,true);
 begin update public.appointments set fee=-1 where id=request_id;raise exception 'FAIL: negative fee accepted';exception when invalid_parameter_value then null;end;
 begin update public.appointments set fee='NaN'::numeric where id=request_id;raise exception 'FAIL: NaN fee accepted';exception when invalid_parameter_value then null;end;
 begin update public.appointments set fee=fee+1 where id=request_id;raise exception 'FAIL: historical fee mutable';exception when invalid_parameter_value then null;end;
 execute 'reset role';update public.service_catalog set base_fee=base_fee+5,student_fee=student_fee+5 where code='barangay_clearance';
 execute 'set local role authenticated';
 if (select fee from public.appointments where id=request_id)<>stored_fee then raise exception 'FAIL: price change alters existing request';end if;
 if public.preview_appointment_fee(resident_record,'barangay_clearance',null)<>quote+5 then raise exception 'FAIL: quote does not use shared fee catalog';end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub','',true);execute 'set local role anon';
 begin perform public.admin_system_analytics();raise exception 'FAIL: anonymous analytics access';exception when insufficient_privilege then null;end;
 execute 'reset role';
end;$test$;
select 'PASS: 36 analytics charts, date semantics, PII exclusion, admin/resident scope, catalog permissions, fee validation, idempotence, and historic snapshots' result;
rollback;
