import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, BellRing, CalendarDays, FileSearch, LayoutDashboard, LogOut, RefreshCw, Search, UserCog, Users } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';
import AdminAnalytics from '../components/AdminAnalytics';
import AdminAnnouncements from '../components/AdminAnnouncements';
import AdminAppointments from '../components/AdminAppointments';
import SortControls from '../components/SortControls';
import { readAllRows } from '../lib/pagination';
import { compareValues, type SortDirection } from '../lib/sorting';
import type { AdminProfile, Resident, ResidentStatus } from '../types/database';

interface Props { tab?: string | null; onLogout: () => void; onReview: (id: string) => void; }
type AdminTab = 'dashboard' | 'records' | 'analytics' | 'announcements' | 'appointments' | 'account';
const TABS: Array<{value:AdminTab;label:string;icon:typeof LayoutDashboard}> = [
  {value:'dashboard',label:'Dashboard',icon:LayoutDashboard},{value:'records',label:'Resident Records',icon:Users},{value:'analytics',label:'Analytics',icon:Activity},{value:'announcements',label:'Announcements',icon:BellRing},{value:'appointments',label:'Appointments',icon:CalendarDays},{value:'account',label:'Profile / Account',icon:UserCog},
];
const STATUS_STYLES: Record<ResidentStatus,string> = { pending_review:'bg-amber-100 text-amber-800', verified:'bg-emerald-100 text-emerald-800', returned:'bg-blue-100 text-blue-800', rejected:'bg-red-100 text-red-800' };
const STATUS_LABELS: Record<ResidentStatus,string> = { pending_review:'Pending Review', verified:'Approved', returned:'Legacy Returned', rejected:'Rejected' };
function normalizeTab(value?:string|null):AdminTab { if(value==='overview')return'dashboard'; if(value==='census')return'records'; return TABS.some((t)=>t.value===value)?value as AdminTab:'dashboard'; }
function fullName(r:Resident){return[r.first_name,r.middle_name,r.last_name,r.suffix].filter(Boolean).join(' ');}
function formatDate(value?:string|null){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat('en-PH',{year:'numeric',month:'short',day:'numeric'}).format(d);}

export default function AdminDashboard({tab,onLogout,onReview}:Props){
  const {user}=useAuth(); const activeTab=normalizeTab(tab);
  const [residents,setResidents]=useState<Resident[]>([]); const [adminProfile,setAdminProfile]=useState<AdminProfile|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [refreshKey,setRefreshKey]=useState(0); const [error,setError]=useState<string|null>(null);
  const [search,setSearch]=useState(''); const [status,setStatus]=useState<'all'|ResidentStatus>('all'); const [sortField,setSortField]=useState('updated_at'); const [sortDirection,setSortDirection]=useState<SortDirection>('desc');

  const fetchData=useCallback(async(manual=false)=>{if(manual)setRefreshing(true);else setLoading(true);setError(null);try{const rows=await readAllRows<Resident>((from,to)=>supabase.from('residents').select('*').order('updated_at',{ascending:false,nullsFirst:false}).order('id',{ascending:true}).range(from,to));setResidents(rows);if(user){const {data,error:profileError}=await supabase.from('admin_profiles').select('*').eq('user_id',user.id).maybeSingle();if(profileError)throw profileError;setAdminProfile(data as AdminProfile|null);}}catch(e){setError(e instanceof Error?e.message:'Unable to load administrator data.');}finally{setLoading(false);setRefreshing(false);}},[user]);
  useEffect(()=>{void fetchData();},[fetchData]);
  const refresh=async()=>{await fetchData(true);setRefreshKey((v)=>v+1);};
  const filtered=useMemo(()=>residents.filter((r)=>{const q=search.trim().toLowerCase();const haystack=`${fullName(r)} ${r.tracking_number??''} ${r.residential_address??''}`.toLowerCase();return(!q||haystack.includes(q))&&(status==='all'||r.status===status);}).sort((a,b)=>{const value=(r:Resident)=>sortField==='last_name'?`${r.last_name} ${r.first_name}`:sortField==='updated_at'?r.updated_at??r.submitted_at:r[sortField as keyof Resident];return compareValues(value(a),value(b),sortDirection)||compareValues(a.id,b.id);}),[residents,search,status,sortField,sortDirection]);
  const stats=useMemo(()=>({total:residents.length,verified:residents.filter(r=>r.status==='verified').length,rejected:residents.filter(r=>r.status==='rejected').length,pending:residents.filter(r=>r.status==='pending_review').length}),[residents]);

  return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-blue-600">Barangay Old Lucban</p><h1 className="mt-1 text-2xl font-bold">Administrator Portal</h1><p className="mt-1 text-sm text-slate-500">Census records, services, analytics, and announcements.</p></div><div className="flex gap-2"><button onClick={()=>void refresh()} disabled={refreshing} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700"><RefreshCw className={refreshing?'animate-spin':''} size={17}/>Refresh</button><button onClick={onLogout} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-red-50 hover:text-red-700"><LogOut size={17}/>Logout</button></div></div></header>
    <nav className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto px-4 py-3 sm:px-6 lg:px-8">{TABS.map(item=>{const Icon=item.icon;return <a key={item.value} href={`#/admin/dashboard?tab=${item.value}`} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold ${activeTab===item.value?'bg-blue-700 text-white':'text-slate-600 hover:bg-blue-50 hover:text-blue-700'}`}><Icon size={17}/>{item.label}</a>;})}</div></nav>
    <main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
      {activeTab==='dashboard'&&<>{<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total Residents" value={stats.total}/><Stat label="Approved" value={stats.verified}/><Stat label="Pending Review" value={stats.pending}/><Stat label="Rejected" value={stats.rejected}/></div>}<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-100 text-blue-700"><LayoutDashboard size={22}/></div><div><h2 className="text-xl font-bold">Census Dashboard</h2><p className="text-sm text-slate-500">Use the navigation above for resident records, analytics, appointments, and announcements.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><Mini label="Latest update" value={residents[0]?.updated_at?formatDate(residents[0].updated_at):'No records'}/><Mini label="Approval rate" value={stats.total?`${Math.round(stats.verified/stats.total*100)}%`:'0%'}/><Mini label="Records needing action" value={stats.pending+stats.rejected}/></div></section></>}
      {activeTab==='records'&&<section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5 sm:p-6"><div className="flex items-center gap-3"><FileSearch className="text-blue-700"/><div><h2 className="text-xl font-bold">Resident Records</h2><p className="text-sm text-slate-500">Search, sort, open, approve, or reject census records.</p></div></div></div><div className="p-5 sm:p-6"><div className="grid gap-3 lg:grid-cols-[1fr_220px]"><label className="relative"><Search className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search name, tracking number, address" className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-4 text-sm"/></label><select value={status} onChange={(e)=>setStatus(e.target.value as 'all'|ResidentStatus)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">All statuses</option><option value="verified">Approved</option><option value="pending_review">Pending Review</option><option value="rejected">Rejected</option><option value="returned">Legacy Returned</option></select></div><div className="mt-4"><SortControls id="resident-records" field={sortField} direction={sortDirection} options={[{value:'updated_at',label:'Last updated'},{value:'last_name',label:'Last name'},{value:'submitted_at',label:'Date submitted'},{value:'status',label:'Status'}]} onFieldChange={setSortField} onDirectionChange={setSortDirection}/></div>{loading?<div className="py-16 text-center text-sm text-slate-500">Loading records…</div>:<div className="mt-5 space-y-3">{filtered.map(r=><article key={r.id} className="flex flex-col gap-4 rounded-2xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{fullName(r)}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${STATUS_STYLES[r.status]}`}>{STATUS_LABELS[r.status]}</span></div><p className="mt-2 text-sm text-slate-500">{r.tracking_number} · {displayAddress(r)}</p><p className="mt-1 text-xs text-slate-400">Updated {formatDate(r.updated_at??r.submitted_at)}</p></div><button onClick={()=>onReview(r.id)} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white">Open Record</button></article>)}{!filtered.length&&<div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 py-12 text-center text-sm text-slate-500">No matching resident records.</div>}</div>}</div></section>}
      {activeTab==='analytics'&&<AdminAnalytics residents={residents}/>} 
      {activeTab==='announcements'&&<AdminAnnouncements adminProfileId={adminProfile?.id} refreshKey={refreshKey}/>} 
      {activeTab==='appointments'&&<AdminAppointments refreshKey={refreshKey}/>} 
      {activeTab==='account'&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold text-blue-700">Administrator account</p><h2 className="mt-1 text-2xl font-bold">Profile / Account</h2><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Mini label="Full Name" value={adminProfile?.full_name??'Not provided'}/><Mini label="Role" value={adminProfile?.role??'Administrator'}/><Mini label="Email" value={user?.email??'Not available'}/><Mini label="Account Status" value={adminProfile?.is_active===false?'Inactive':'Active'}/></dl></section>}
    </main></div>;
}
function displayAddress(r:Resident){return r.residential_address||`${r.barangay}, ${r.city_municipality}`;}
function Stat({label,value}:{label:string;value:number}){return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>;}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-bold capitalize text-slate-800">{value}</dd></div>;}
