// Preview-branch fixture. This module is excluded from the production tree.
const residents=Array.from({length:27},(_,i)=>({id:`r${i}`,user_id:`u${i}`,first_name:i===0?'Sample':'Resident',middle_name:'',last_name:i===0?'Resident':`Record ${i+1}`,suffix:i===0?'Jr.':'',tracking_number:`UI-${1000+i}`,region:'Cordillera Administrative Region (CAR)',province:'Benguet',city_municipality:'Baguio City',barangay:'Old Lucban',birth_date:i%2?'1985-03-10':'2000-04-10',birth_place:'Baguio City',sex:i%2?'Female':'Male',civil_status:i%3?'Single':'Married',religion:'Not specified',citizenship:'Filipino',profession_occupation:i%3?'Student':'Teacher',contact_number:'09170000000',email_address:`resident${i}@example.invalid`,residential_address:'Sample address, Old Lucban, Baguio City',highest_education:'College',education_status:'Currently Studying',tenurial_status:i%3?'Owner':'Renter',monthly_rent:i%3?null:5000,status:i%3?'verified':'pending_review',updated_at:'2026-10-06T03:00:00Z',submitted_at:'2026-10-01T02:00:00Z',created_at:'2026-10-01T02:00:00Z',search_text:`Sample Resident Record ${i+1} UI-${1000+i} Sample address`}));
const appointments=Array.from({length:25},(_,i)=>({id:`a${i}`,user_id:i<4?'u0':`u${i}`,resident_id:i<4?'r0':`r${i}`,residents:residents[i<4?0:i],status:i===1?'completed':i===2?'cancelled':i%2?'confirmed':'pending',service_type:i%2?'barangay_clearance':'certificate_of_residency',service_purpose:i%2?null:'low_income',fee:i%2?130:30,appointment_date:i===1?'2026-10-01':'2026-10-09',appointment_time:'09:00:00',created_at:'2026-10-05T02:00:00Z',completed_at:i===1?'2026-10-01T02:00:00Z':null,cancelled_at:i===2?'2026-10-05T03:00:00Z':null,cancellation_reason:i===2?'Schedule changed':null,purpose:'Sample service request for UI review',service_label:i%2?'Barangay Clearance':'Certificate of Residency',search_text:`Sample Resident ${i} Low Income`}));
const categories=[{id:'c0',name:'FHONA'},{id:'c1',name:'PWD'},{id:'c2',name:'Senior Citizen'},{id:'c3',name:'Indigenous People'},{id:'c4',name:'Others'}];
const announcements=Array.from({length:9},(_,i)=>({id:`n${i}`,title:i===0?'Community service schedule':`Barangay update ${i+1}`,message:('This is a sample announcement used only to review the new interface. Please check the barangay service schedule and bring the required documents. ').repeat(i===0?6:1),priority:i===2?'important':'info',audience:'all',is_published:true,archived:i===8,expires_at:null,image_path:i===0?'sample/banner.svg':null,created_at:'2026-10-05T02:00:00Z',updated_at:'2026-10-05T02:00:00Z',published_at:'2026-10-05T02:00:00Z',archived_at:i===8?'2026-10-05T03:00:00Z':null}));
const period={id:'p0',resident_id:'r0',start_date:'2026-01-01',end_date:null,initial_classification:'temporary',current_classification:'resident',resident_from:'2026-07-01'};
const session={user:{id:'u0',email:'resident0@example.invalid'}};let authListener;
function from(table){let filters=[],orders=[],range,limit,head=false,operation='select',values;
 const q={select(_columns,options){head=Boolean(options?.head);return q},eq(k,v){filters.push([k,v]);return q},in(k,v){filters.push([k,v]);return q},is(k,v){filters.push([k,v]);return q},ilike(k,v){filters.push([k,v]);return q},or(){return q},gte(){return q},lte(){return q},not(){return q},neq(){return q},order(k,o){orders.push([k,o?.ascending!==false]);return q},range(a,b){range=[a,b];return q},limit(v){limit=v;return q},update(v){operation='update';values=v;return q},insert(v){operation='insert';values=v;return q},delete(){operation='delete';return q},single(){return run(true)},maybeSingle(){return run(true)},then(resolve,reject){return run(false).then(resolve,reject)}};
 async function run(single){if(table==='admin_profiles')return{data:{id:'profile',user_id:'u0',full_name:'Sample Administrator',is_active:true,created_at:'2026-01-01T00:00:00Z'},error:null};
 let rows=table==='categories'?categories:table==='resident_categories'?[{resident_id:'r0',category_id:'c0',categories:{name:'FHONA'}}]:table==='residency_periods'||table==='residency_current'?[period]:table==='residency_history'?[{resident_id:'r0',period_id:'p0',effective_date:'2026-07-01',classification:'resident',reason:'Six calendar months of continuous residence'}]:table.includes('announcement')?announcements:table==='appointments'||table.includes('service_records')?appointments:table==='residents'||table==='admin_resident_records'?residents:[];
 rows=rows.filter(row=>filters.every(([k,v])=>Array.isArray(v)?v.includes(row[k]):typeof v==='string'&&v.startsWith('%')?String(row[k]||'').toLowerCase().includes(v.slice(1,-1).toLowerCase()):row[k]===v));
 if(operation==='update')rows.forEach(row=>Object.assign(row,values));const count=rows.length;
 rows=[...rows].sort((a,b)=>{for(const[k,asc]of orders){const c=String(a[k]||'').localeCompare(String(b[k]||''));if(c)return asc?c:-c}return 0});if(range)rows=rows.slice(range[0],range[1]+1);if(limit)rows=rows.slice(0,limit);
 return{data:head?null:single?(rows[0]||null):rows.map(r=>({...r})),count,error:null};}return q;}
export const supabase={from,auth:{getSession:async()=>({data:{session},error:null}),onAuthStateChange:cb=>{authListener=cb;return{data:{subscription:{unsubscribe(){}}}}},signInWithPassword:async()=>({data:{session,user:session.user},error:null}),signUp:async()=>({data:{session:null,user:{...session.user,identities:[{}]}},error:null}),resend:async()=>({error:null}),resetPasswordForEmail:async()=>({error:null}),signOut:async()=>{authListener?.('SIGNED_OUT',null);return{error:null}}},rpc:async(name,args)=>({error:null,data:name==='admin_census_analytics'?{total:18,excluded:9,age:[{label:'Children (0–12)',count:2},{label:'Youth (13–24)',count:5},{label:'Adults (25–59)',count:8},{label:'Seniors (60+)',count:3}],gender:[{label:'Female',count:10},{label:'Male',count:8}],civil:[{label:'Single',count:10},{label:'Married',count:6},{label:'Widowed',count:2}],education:[{label:'College',count:9},{label:'High School',count:6},{label:'Elementary',count:3}]}:name==='admin_dashboard_summary'?{stats:{total:27,verified:18,pending:9,rejected:0},appointments:{total:25,today:4,completedToday:1,pending:13},announcements:{active:8,archived:1,published:8},recentResidents:residents.slice(0,5)}:name==='preview_appointment_fee'?args.p_service_type==='barangay_clearance'?130:args.p_service_purpose==='low_income'?0:30:name==='check_registration_email'?{valid:true,registered:false,rate_limited:false}:{success:true,booked:true}}),storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:'/ui-review/banner.svg'},error:null}),upload:async()=>({data:{path:'preview/image.jpg'},error:null}),remove:async()=>({error:null})})}};
